### ISSUE TITLE
Possibility to freeze fields when importing a new pdf

### ISSUE THREAD

**Issue by OuraN2O** [Vilhelm-Ian/anki-search-inside-add-card#10]
With my activity I have to add multiple pdf one after the other and it would be really great to be able to pick wich field I'd like to keep when clicking on "create and keep open". Sometimes I just have to change a number in the title and have to retype everything. 
Honestly it's not as important as the other feature request I made about multiple links to one pdf but it would be cool

**Comment by OuraN2O** [comment]
If you have even the slightest idea about how to implement this feature I'm open to hearing it and try myself

**Comment by Vilhelm-Ian** [comment]
i will take a look at the source code and see if I can figure out it

**Comment by Vilhelm-Ian** [comment]
@OuraN2O I can't find in which file is the new_note dialog written

**Comment by Vilhelm-Ian** [comment]
@OuraN2O https://github.com/Vilhelm-Ian/anki-search-inside-add-card/tree/frozen_field I've got it working the only thing left for me to do is figure out how to change the svg color something. I wanna finish this feature. But I am open to critism for the changes till now

**Comment by OuraN2O** [comment]
> @OuraN2O https://github.com/Vilhelm-Ian/anki-search-inside-add-card/tree/frozen_field I've got it working the only thing left for me to do is figure out how to change the svg color something. I wanna finish this feature. But I am open to critism for the changes till now

Hi ! 
I downloaded the src file in the frozen field branch but I don't see how it should work, could you help me ? I don't see the toggle button and when I click on "create and keep open" it does the same thing as before
![image](https://github.com/Vilhelm-Ian/anki-search-inside-add-card/assets/151692686/85608c18-b4f3-44a4-ae1e-259c66c3cd88)

**Comment by Vilhelm-Ian** [comment]
@OuraN2O it's cause I forgot to commit the svg I shall do it again sorroy

**Comment by OuraN2O** [comment]
Works really well ! Thank you. Except obviously the color of the svg to change when toggling but you already acknowleged that so that's good. Maybe add the same possibilty to the "text" field too ?

**Comment by Vilhelm-Ian** [comment]
okie dokie. OuraN20 I have a bunch of responsobilities. Hope you have understanding for the slow progress

**Comment by OuraN2O** [comment]
Yeah absolutely no worries. I'm a med student I know what it's like to not have time :joy: and you're already doing a good job

**Comment by Vilhelm-Ian** [comment]
> Yeah absolutely no worries. I'm a med student I know what it's like to not have time 😂 and you're already doing a good job

YAY a different medstudent. I just got my liscenec

**Comment by Vilhelm-Ian** [comment]
@OuraN2O  I added the feature thanks for your patients

**Comment by OuraN2O** [comment]
Works perfect, thx !
