### ISSUE TITLE
Import from webpage doesn't work

### ISSUE THREAD

**Issue by Jam-u** [Vilhelm-Ian/anki-search-inside-add-card#11]
**Describe the bug**
When I try to import a new source from an external webpage using the Webpage to PDF option, an error message pops up. When I go to review sources in my queue, it says the path for the source may be incorrect.

**To Reproduce**
1. Go to SIAC --> Import --> Create New
2. Go to Source section of the dialog
3. Click on the Source dropdown menu
4. Click Webpage to PDF (URL) option
5. Input url and optional PDF Name (I used this article: https://edu.gcfglobal.org/en/computerbasics/what-is-a-computer/1/)
6. Click Import (after inputting other information like title)
7. See error

**Expected behavior**
I expected it to convert the webpage into a pdf with the name of the pdf I entered into the box without an error message. I also expected that pdf to show up in my queue.

**Screenshots**
The dialogue menu where clicking import causes the problem:
![image](https://github.com/Vilhelm-Ian/anki-search-inside-add-card/assets/74335787/636ab1b2-6303-44b5-9bc4-87b57644dcc7)
Showed this message when I tried to see if it still went to my queue:
![image](https://github.com/Vilhelm-Ian/anki-search-inside-add-card/assets/74335787/3abe0efa-dc67-4d25-948c-fba7107c0505)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Anki version: 23.12.1 (Qt6)
 
**Additional Information**
Copy of Debug Info Anki gave me:
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.19045

Traceback (most recent call last):
  File "C:\Users\munac\AppData\Roaming\Anki2\addons21\572933442\src\utility\misc.py", line 341, in save_pdf
    printer = QPrinter()
NameError: name 'QPrinter' is not defined

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
FSRS4Anki Helper ['759844606', 2024-03-20T00:00, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T03:15, 'None', '']
Searching PDF Reading  Note-Taking in Add Dialog - Qt6 port ['572933442', 2024-03-31T06:58, 'None', mod]

===IDs of active AnkiWeb add-ons===
1374772155 572933442 759844606

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by OuraN2O** [comment]
I also have this error on the 24.04 qt6 version. I'll take a look

**Comment by OuraN2O** [comment]
Seems like I solved your issue. Don't hesitate to test if it works on your system too

**Comment by Jam-u** [comment]
> Seems like I solved your issue. Don't hesitate to test if it works on your system too

How do I go about being able to update my add-on to incorporate your changes. I clicked the "Check for Updates" in  the add-on dialogue but it said there were no updates.

**Comment by Vilhelm-Ian** [comment]
@Jam-u I uploaded the changes to ankiweb. Can you download it from there and tell me if everything is ok

**Comment by Jam-u** [comment]
Thank you @OuraN2O. I decided to wait for it to be pushed to ankiweb because I'm not the most proficient with Git and GitHub.
@Vilhelm-Ian I updated the add-on and can confirm that it works. Thank you.
