### ISSUE TITLE
Any plans to upload this to ankiweb, seeing that the original addon seems to be abandoned?

### ISSUE THREAD

**Issue by Arbitrate3280** [Vilhelm-Ian/anki-search-inside-add-card#5]

**Comment by Vilhelm-Ian** [comment]
@Arbitrate3280 It's already uploaded to ankiweb. The latest update isn't. Because I haven't figured a shell script how to zip the files on linux.

https://ankiweb.net/shared/info/572933442

**Comment by Arbitrate3280** [comment]
Sorry, hadn't noticed it before. Thanks!!
