### ISSUE TITLE
When tapping to a setting in the top, the window just scrolls down by itself

### ISSUE THREAD

**Issue by Fastball2880** [Vilhelm-Ian/anki-search-inside-add-card#7]
**Describe the bug**
When I want to tap a setting in the top like "Setting & Info", it keeps scrolling down for no apparent reason. Even with Auto-hide, it does that too.

**To Reproduce**
1. Go to "Add" to add decks.
2. Click on 'Setting & Info'.
3. The window just scrolls down by itself

**Expected behavior**
The window will just stay intact and just interact with the tabs on top of the window.

**Screenshots**

https://github.com/Vilhelm-Ian/anki-search-inside-add-card/assets/147415340/6f5c7214-3c08-4462-a27d-1614fd03e83d

**Environment (please complete the following information):**
 - OS: Microsoft Windows 10 Pro 10.0.19044 Build 19044
 - Anki version: Version ⁨23.12.1 (1a1d4d54)⁩

**Comment by OuraN2O** [comment]
Hello, not really a fix but if it bothers you, you can close the "tags adder" at the bottom of your window and it won't happen anymore

**Comment by Vilhelm-Ian** [comment]
i was not getting notification I will take a look at the most of the issues now

**Comment by Vilhelm-Ian** [comment]
@Fastball2880 it's fixed in the latest commit
