### ISSUE TITLE
Can't import pdf

### ISSUE THREAD

**Issue by OuraN2O** [Vilhelm-Ian/anki-search-inside-add-card#8]
**Describe the bug**
Can't import new pdf, pop-up appears with "anki encountered a problem"

**To Reproduce**
1. Try importing a new pdf (with the button of by dragging a pdf)
2. See error

**Expected behavior**
Should be able to import

**Screenshots**
![image](https://github.com/Vilhelm-Ian/anki-search-inside-add-card/assets/151692686/251352ed-a916-4e2a-8dee-48af8e35df3b)
**Environment (please complete the following information):**
 - OS: Windows 11 
 - Anki version 23.12.1 Qt6.6.1

**Comment by OuraN2O** [comment]
Seems to be working on Linux (anki 23.12.1, Qt6.6.2). Weird that it stopped on my windows machine because I didn't update anything nor changed anything

**Comment by OuraN2O** [comment]
Seems to be working on linux (anki 23.12.1 and Qt6.6.2). Weird that it stopped on my windows machine because from the time I was able to import pdfs I didn't update nor change anything.
(Didn't mean to close the issue a minute ago, missclick)

**Comment by OuraN2O** [comment]
Hello, same issue is appearing on my Linux device. I found a way to fix the problem. It was to download the files and copy them in the addon folder and rewrite. But it doesn't work anymore. Reinstalling the addon completely doesn't do much either. I have the same problems as my first post

**Comment by OuraN2O** [comment]
[Here is the debug info provided by anki]


Anki 23.12.1 (1a1d4d54) (src) (ao)
Python 3.11.8 Qt 6.6.2 PyQt 6.6.1
Platform: Linux-6.7.8-arch1-1-x86_64-with-glibc2.39

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/aqt/webview.py", line 50, in cmd
    return json.dumps(self.onCmd(str))
                      ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aqt/webview.py", line 157, in _onCmd
    return self._onBridgeCmd(str)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aqt/webview.py", line 680, in _onBridgeCmd
    handled, result = gui_hooks.webview_did_receive_js_message(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/_aqt/hooks.py", line 4481, in __call__
    handled = filter(handled, message, context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/.local/share/Anki2/addons21/572933442/src/command_parsing.py", line 345, in expanded_on_bridge_cmd
    elif handle_notes(self, cmd):
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/.local/share/Anki2/addons21/572933442/src/cmds/cmds_notes.py", line 57, in handle
    NoteEditor(editor.parentWindow, id)
  File "/home/admin/.local/share/Anki2/addons21/572933442/src/dialogs/editor.py", line 188, in __init__
    self.setup_ui()
  File "/home/admin/.local/share/Anki2/addons21/572933442/src/dialogs/editor.py", line 224, in setup_ui
    self.create_tab     = CreateTab(self)
                          ^^^^^^^^^^^^^^^
  File "/home/admin/.local/share/Anki2/addons21/572933442/src/dialogs/editor.py", line 601, in __init__
    self.slider = QtPrioritySlider(self.parent.priority, self.parent.note_id, show_spec_sched=False, show_similar=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/.local/share/Anki2/addons21/572933442/src/dialogs/components.py", line 58, in __init__
    self.slider.setValue(prio_default)
TypeError: setValue(self, a0: int): argument 1 has unexpected type 'float'

**Comment by Arbitrate3280** [comment]
Same thing happening here, I'm on Windows 11

**Comment by OuraN2O** [comment]
> Same thing happening here, I'm on Windows 11

Hello, I made a fork of this repo with the fixes that I made. You can go to it and download the files then copy them into your already existing addon's folder.
https://github.com/OuraN2O/anki-search-inside-add-card-SIAC
It should work right out of the box and if you find any bugs feel free to open an issue on my github.

Hope it suits you !
